# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Serverless Patterns v1 - Data store

# Globals:

Resources:
  UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: !Sub  ${AWS::StackName}-Users
        AttributeDefinitions:
          - AttributeName: userid
            AttributeType: S
        KeySchema:
          - AttributeName: userid
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

Outputs:
  UsersTable:
      Description: DynamoDB Users table
      Value: !Ref UsersTable